package com.sceince.model;

public class UserToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.token
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.userId
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.type
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.times
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.remainedTimes
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer remainedtimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.expiredTime
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer expiredtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.createdTime
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer createdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_token.data
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.id
     *
     * @return the value of sc_user_token.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.id
     *
     * @param id the value for sc_user_token.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.token
     *
     * @return the value of sc_user_token.token
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.token
     *
     * @param token the value for sc_user_token.token
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.userId
     *
     * @return the value of sc_user_token.userId
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.userId
     *
     * @param userid the value for sc_user_token.userId
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.type
     *
     * @return the value of sc_user_token.type
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.type
     *
     * @param type the value for sc_user_token.type
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.times
     *
     * @return the value of sc_user_token.times
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.times
     *
     * @param times the value for sc_user_token.times
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.remainedTimes
     *
     * @return the value of sc_user_token.remainedTimes
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getRemainedtimes() {
        return remainedtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.remainedTimes
     *
     * @param remainedtimes the value for sc_user_token.remainedTimes
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setRemainedtimes(Integer remainedtimes) {
        this.remainedtimes = remainedtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.expiredTime
     *
     * @return the value of sc_user_token.expiredTime
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getExpiredtime() {
        return expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.expiredTime
     *
     * @param expiredtime the value for sc_user_token.expiredTime
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setExpiredtime(Integer expiredtime) {
        this.expiredtime = expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.createdTime
     *
     * @return the value of sc_user_token.createdTime
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.createdTime
     *
     * @param createdtime the value for sc_user_token.createdTime
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setCreatedtime(Integer createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_token.data
     *
     * @return the value of sc_user_token.data
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_token.data
     *
     * @param data the value for sc_user_token.data
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setData(String data) {
        this.data = data;
    }
}