package com.sceince.model;

import java.util.Date;


public class UserProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.truename
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.idcard
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.gender
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.sex
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.iam
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String iam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.birthday
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.city
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Short city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.qq
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.company
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.job
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Short job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.school
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.class
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.weibo
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String weibo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.weixin
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_profile.site
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String site;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.id
     *
     * @return the value of sc_user_profile.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.id
     *
     * @param id the value for sc_user_profile.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.truename
     *
     * @return the value of sc_user_profile.truename
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.truename
     *
     * @param truename the value for sc_user_profile.truename
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.idcard
     *
     * @return the value of sc_user_profile.idcard
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.idcard
     *
     * @param idcard the value for sc_user_profile.idcard
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.gender
     *
     * @return the value of sc_user_profile.gender
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.gender
     *
     * @param gender the value for sc_user_profile.gender
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.sex
     *
     * @return the value of sc_user_profile.sex
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.sex
     *
     * @param sex the value for sc_user_profile.sex
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.iam
     *
     * @return the value of sc_user_profile.iam
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getIam() {
        return iam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.iam
     *
     * @param iam the value for sc_user_profile.iam
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setIam(String iam) {
        this.iam = iam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.birthday
     *
     * @return the value of sc_user_profile.birthday
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.birthday
     *
     * @param birthday the value for sc_user_profile.birthday
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.city
     *
     * @return the value of sc_user_profile.city
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.city
     *
     * @param city the value for sc_user_profile.city
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.qq
     *
     * @return the value of sc_user_profile.qq
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.qq
     *
     * @param qq the value for sc_user_profile.qq
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.company
     *
     * @return the value of sc_user_profile.company
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.company
     *
     * @param company the value for sc_user_profile.company
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.job
     *
     * @return the value of sc_user_profile.job
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Short getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.job
     *
     * @param job the value for sc_user_profile.job
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setJob(Short job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.school
     *
     * @return the value of sc_user_profile.school
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.school
     *
     * @param school the value for sc_user_profile.school
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.class
     *
     * @return the value of sc_user_profile.class
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.class
     *
     * @param class the value for sc_user_profile.class
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setClass(String classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.weibo
     *
     * @return the value of sc_user_profile.weibo
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.weibo
     *
     * @param weibo the value for sc_user_profile.weibo
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.weixin
     *
     * @return the value of sc_user_profile.weixin
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.weixin
     *
     * @param weixin the value for sc_user_profile.weixin
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_profile.site
     *
     * @return the value of sc_user_profile.site
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_profile.site
     *
     * @param site the value for sc_user_profile.site
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setSite(String site) {
        this.site = site;
    }
}