package com.sceince.model;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.userId
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.name
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.mobile
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.zipcode
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.province
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.city
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.town
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Integer town;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.address
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_address.defaulted
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    private Byte defaulted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.id
     *
     * @return the value of sc_user_address.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.id
     *
     * @param id the value for sc_user_address.id
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.userId
     *
     * @return the value of sc_user_address.userId
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.userId
     *
     * @param userid the value for sc_user_address.userId
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.name
     *
     * @return the value of sc_user_address.name
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.name
     *
     * @param name the value for sc_user_address.name
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.mobile
     *
     * @return the value of sc_user_address.mobile
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.mobile
     *
     * @param mobile the value for sc_user_address.mobile
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.zipcode
     *
     * @return the value of sc_user_address.zipcode
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.zipcode
     *
     * @param zipcode the value for sc_user_address.zipcode
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.province
     *
     * @return the value of sc_user_address.province
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.province
     *
     * @param province the value for sc_user_address.province
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.city
     *
     * @return the value of sc_user_address.city
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.city
     *
     * @param city the value for sc_user_address.city
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.town
     *
     * @return the value of sc_user_address.town
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Integer getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.town
     *
     * @param town the value for sc_user_address.town
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setTown(Integer town) {
        this.town = town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.address
     *
     * @return the value of sc_user_address.address
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.address
     *
     * @param address the value for sc_user_address.address
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_address.defaulted
     *
     * @return the value of sc_user_address.defaulted
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public Byte getdefaulted() {
        return defaulted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_address.defaulted
     *
     * @param defaulted the value for sc_user_address.defaulted
     *
     * @mbg.generated Wed Sep 27 09:54:13 CST 2017
     */
    public void setdefaulted(Byte defaulted) {
        this.defaulted = defaulted;
    }
}